{
    "dtach": true, 
    "uid": "1000", 
    "locale": "en_US", 
    "user_logs_max_age": "30d", 
    "pam_service": "login", 
    "syslog_facility": "daemon", 
    "js_init": "", 
    "cookie_secret": "OTFmNWRiOTZjMTJlNDc2ZWE0ZTJhMWRhYWRjOTc2MmUyM", 
    "enable_unix_socket": false, 
    "session_timeout": "5d", 
    "port": 10443, 
    "url_prefix": "/", 
    "user_dir": "/home/jimmy/Desktop/GateOne/users", 
    "settings_dir": "/home/jimmy/Desktop/GateOne/conf.d", 
    "unix_socket_mode": "0600", 
    "log_rotate_mode": "size", 
    "certificate": "/home/jimmy/Desktop/GateOne/ssl/certificate.pem", 
    "log_rotate_interval": 1, 
    "log_to_stderr": null, 
    "log_rotate_when": "midnight", 
    "gid": "1000", 
    "version": null, 
    "pid_file": "/home/jimmy/Desktop/GateOne/gateone.pid", 
    "command": null, 
    "pam_realm": "jimmy-VirtualBox", 
    "configure": false, 
    "sso_service": "HTTP", 
    "cli_overrides": [], 
    "https_redirect": false, 
    "auth": null, 
    "api_keys": {
        "ZDRhMTA1ZjIwZDY2NDc3N2I4ZmZlNzQzM2ZiMTUxN2M4N": "YTA4ZWYzZjYzNWE5NDIyMmExMTZiZDE3MzdhNTk1NWY0M"
    }, 
    "disable_ssl": false, 
    "ca_certs": null, 
    "cache_dir": "/home/jimmy/Desktop/GateOne/cache", 
    "syslog_session_logging": false, 
    "address": "", 
    "logging": "info", 
    "multiprocessing_workers": null, 
    "log_file_num_backups": 10, 
    "sso_keytab": null, 
    "origins": [
        "localhost:10443", 
        "127.0.0.1:10443", 
        "jimmy-VirtualBox:10443", 
        "127.0.1.1:10443"
    ], 
    "embedded": false, 
    "session_logging": true, 
    "unix_socket_path": "/tmp/gateone.sock", 
    "ssl_auth": "none", 
    "log_file_max_size": 100000000, 
    "session_dir": "/home/jimmy/Desktop/GateOne/sessions", 
    "sso_realm": null, 
    "debug": false, 
    "api_timestamp_window": 30, 
    "keyfile": "/home/jimmy/Desktop/GateOne/ssl/keyfile.pem", 
    "log_file_prefix": "/home/jimmy/Desktop/GateOne/logs/gateone.log"
}

